/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:3d5af424-6c0a-4eb8-8d97-17db55c0317a",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_S0zlYZyqM",
    "aws_user_pools_web_client_id": "3rotblchkeo0ek7t97j63ku78r",
    "oauth": {}
};


export default awsmobile;
